#!/bin/bash
# downloads a local copy of qemu on docker-hub build machines
curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v5.2.0-1/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
